-- OpenGTM Jobs Engine Database Schema
-- Core tables for GTM automation

-- Accounts table (from ZoomInfo CSV)
CREATE TABLE IF NOT EXISTS accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zoominfo_company_id TEXT UNIQUE,
  company_name TEXT NOT NULL,
  website TEXT,
  primary_industry TEXT,
  primary_sub_industry TEXT,
  revenue_thousands NUMERIC,
  employees INTEGER,
  city TEXT,
  state TEXT,
  country TEXT,
  icp_score NUMERIC DEFAULT 0,
  tier TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Contacts table (from ZoomInfo CSV)
CREATE TABLE IF NOT EXISTS contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  zoominfo_contact_id TEXT UNIQUE,
  account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
  first_name TEXT,
  last_name TEXT,
  full_name TEXT,
  job_title TEXT,
  management_level TEXT,
  job_function TEXT,
  department TEXT,
  email TEXT,
  persona TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Personas (normalized from contacts)
CREATE TABLE IF NOT EXISTS personas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  job_functions TEXT[],
  management_levels TEXT[],
  contact_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- GTM Agents (the 18 jobs)
CREATE TABLE IF NOT EXISTS agents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  gtm_stage TEXT NOT NULL,
  gtm_goal TEXT NOT NULL,
  owner_role TEXT,
  required_data TEXT[],
  skills TEXT[],
  workflow TEXT,
  outputs TEXT[],
  prompt TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Audiences (generated by agents)
CREATE TABLE IF NOT EXISTS audiences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  agent_id UUID REFERENCES agents(id),
  filters JSONB,
  account_count INTEGER DEFAULT 0,
  contact_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Audience members (junction table)
CREATE TABLE IF NOT EXISTS audience_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audience_id UUID REFERENCES audiences(id) ON DELETE CASCADE,
  account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
  score NUMERIC,
  UNIQUE(audience_id, account_id)
);

-- Plays (execution plans generated by agents)
CREATE TABLE IF NOT EXISTS plays (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  audience_id UUID REFERENCES audiences(id),
  agent_id UUID REFERENCES agents(id),
  channels TEXT[],
  steps JSONB,
  status TEXT DEFAULT 'draft',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Agent runs (execution history)
CREATE TABLE IF NOT EXISTS agent_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_id UUID REFERENCES agents(id),
  status TEXT DEFAULT 'pending',
  input_data JSONB,
  output_data JSONB,
  rationale TEXT,
  audience_id UUID REFERENCES audiences(id),
  play_id UUID REFERENCES plays(id),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  error TEXT
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_contacts_account ON contacts(account_id);
CREATE INDEX IF NOT EXISTS idx_accounts_industry ON accounts(primary_industry);
CREATE INDEX IF NOT EXISTS idx_accounts_icp_score ON accounts(icp_score DESC);
CREATE INDEX IF NOT EXISTS idx_agent_runs_agent ON agent_runs(agent_id);
CREATE INDEX IF NOT EXISTS idx_audience_accounts_audience ON audience_accounts(audience_id);
CREATE INDEX IF NOT EXISTS idx_contacts_persona ON contacts(persona);
CREATE INDEX IF NOT EXISTS idx_agents_gtm_stage ON agents(gtm_stage);
